from parseur_edi import ParseurEdi
import datetime

def test_parseur_edi():
    edi_file = "src/tests/113192.edi"
    ref_dic = {
        'ACOMPTE': -521.09,
        'TVA': 296.13,
        'date': datetime.datetime(2019, 5, 14, 0, 0),
        'groups': {
            '001 SURGELE': {
                'items': [
                    ['12528-006','MUFFIN PEPITES CHOCO', 1, 13.3],
                    ['5-300','VIANDE 10/1', 8, 514.8],
                                                  [   '6-468',
                                                      'VIANDE CHAROLAISE '
                                                      'SIGNATURE2',
                                                      1,
                                                      70.1],
                                                  [   '1146-056',
                                                      'VIANDE 3/1',
                                                      5,
                                                      326.8],
                                                  [   '407-783',
                                                      'NUGGETS -C',
                                                      6,
                                                      353.4],
                                                  [   '1395-091',
                                                      'CHICKEN PREMIERE N3 -C',
                                                      2,
                                                      124.18],
                                                  [   '7131-101',
                                                      'BACON FUME 2',
                                                      1,
                                                      46.17],
                                                  [   '8-026',
                                                      'FILET POISSON COLIN MSC',
                                                      2,
                                                      100.56],
                                                  [   '757-012',
                                                      'CHEVRE PANE',
                                                      2,
                                                      67.66],
                                                  [   '1-753',
                                                      'PAIN FOCACCIA AUX '
                                                      'HERBES',
                                                      3,
                                                      25.11],
                                                  [   '2-015',
                                                      'PAIN ROYAL CONGELE',
                                                      1,
                                                      5.23],
                                                  [   '6053-018',
                                                      'PAIN SHINY 4,5P',
                                                      5,
                                                      22.9],
                                                  [   '7889-006',
                                                      'PAIN BIG TASTY',
                                                      3,
                                                      16.89],
                                                  [   '8672-040',
                                                      'PAIN 280',
                                                      3,
                                                      18.72],
                                                  [   '8272-201',
                                                      'PAIN CBO',
                                                      2,
                                                      13.92],
                                                  [   '2683-007',
                                                      'TORTILLA GRAND WRAP',
                                                      3,
                                                      27.18],
                                                  [   '3114-020',
                                                      'TORTILLA PETIT WRAP',
                                                      5,
                                                      30.0],
                                                  [   '12701-000',
                                                      'BROWNIE CHOCO-NOISETTE',
                                                      1,
                                                      13.11],
                                                  [   '10332-025',
                                                      'PAIN FIRST',
                                                      10,
                                                      74.8],
                                                  [   '4-813',
                                                      'FRITES MC CAIN NEW OIL',
                                                      27,
                                                      355.59],
                                                  [   '6776-050',
                                                      'POTATOES',
                                                      16,
                                                      197.92],
                                                  [   '4430-002',
                                                      'POULET WRAP 3 -C',
                                                      3,
                                                      167.73],
                                                  [   '3776-081',
                                                      'DONUTS SUCRE',
                                                      1,
                                                      9.8],
                                                  [   '11720-029',
                                                      'DONUTS SAVEUR CHOCOLAT',
                                                      1,
                                                      18.78],
                                                  [   '14133-000',
                                                      'COOKIE PECAN CARAMEL '
                                                      'COMPTOIR',
                                                      1,
                                                      20.12]],
                                     'montant': 2634.77,
                                     'quantite': '113'},
                  '002 ALIMENTAIRE': {   'items': [   [   '4180-105',
                                                          'SAUCE SIGNATURE '
                                                          'GOUT BARBECUE',
                                                          1,
                                                          8.24],
                                                      [   '6207-045',
                                                          'BERLINGO POMME SSA '
                                                          '100% FRUIT',
                                                          1,
                                                          5.85],
                                                      [   '1870-030',
                                                          'OIGNONS FRITS',
                                                          1,
                                                          11.53],
                                                      [   '13-073',
                                                          'FROMAGE CHEDDAR',
                                                          4,
                                                          227.72],
                                                      [   '2303-024',
                                                          'EMMENTAL FONDU CROQ',
                                                          2,
                                                          116.08],
                                                      [   '3940-041',
                                                          'LAIT DEMI ECREME 1 '
                                                          'LITRE',
                                                          3,
                                                          13.65],
                                                      [   '11-321',
                                                          'SHAKE MIX 1X10L',
                                                          1,
                                                          9.58],
                                                      [   '12-444',
                                                          'SUNDAE MIX 1X10L',
                                                          9,
                                                          97.74],
                                                      [   '10473-012',
                                                          'YAOURT HM PECHE BIO',
                                                          5,
                                                          17.15],
                                                      [   '55-065',
                                                          'SAUCE BIG MAC X 12',
                                                          1,
                                                          16.25],
                                                      [   '7919-108',
                                                          'SAUCE BIG TASTY 3',
                                                          1,
                                                          11.97],
                                                      [   '5297-051',
                                                          'SAUCE RANCH '
                                                          'INTENSIVE 500GR',
                                                          3,
                                                          31.98],
                                                      [   '1-021',
                                                          'PAIN REG.   FRAIS',
                                                          27,
                                                          133.11],
                                                      [   '3-213',
                                                          'PAIN BIGMAC FRAIS 2',
                                                          22,
                                                          71.5],
                                                      [   '5743-016',
                                                          'LIPTON ICE TEA 2',
                                                          1,
                                                          35.54],
                                                      [   '19-363',
                                                          'COCA COLA BIB HR '
                                                          '19L',
                                                          3,
                                                          322.44],
                                                      [   '5054-017',
                                                          'COCA ZERO BIB HR 5L',
                                                          2,
                                                          66.22],
                                                      [   '21-381',
                                                          'FANTA ORANGE 19L',
                                                          1,
                                                          102.42],
                                                      [   '3769-030',
                                                          'EVIAN 50',
                                                          2,
                                                          25.0],
                                                      [   '3769-049',
                                                          'BADOIT 33',
                                                          2,
                                                          33.22],
                                                      [   '3769-098',
                                                          'EVIAN 33CL PET *24',
                                                          2,
                                                          20.68],
                                                      [   '8347-018',
                                                          'BADOIT 50',
                                                          2,
                                                          39.24],
                                                      [   '1094-003',
                                                          'SIROP FRAMBOISE '
                                                          'MYRTILLE SHAKE',
                                                          1,
                                                          14.26],
                                                      [   '1912-051',
                                                          'TOPPING MC FLURRY '
                                                          'DAIM 2',
                                                          1,
                                                          48.52],
                                                      [   '408-043',
                                                          'SCE BARBECUE X125',
                                                          4,
                                                          25.88],
                                                      [   '8158-018',
                                                          'SAUCE CREAMY DELUXE',
                                                          8,
                                                          105.76],
                                                      [   '2679-079',
                                                          'KETCHUP BIB CUISINE '
                                                          'N2',
                                                          2,
                                                          22.8],
                                                      [   '45-312',
                                                          'KETCHUP DOSETTE',
                                                          1,
                                                          13.43],
                                                      [   '3677-024',
                                                          'SAUCE FRITES 14ML 2',
                                                          1,
                                                          17.19],
                                                      [   '63-047',
                                                          'CORNICHON X6,8 KG',
                                                          2,
                                                          18.88],
                                                      [   '2589-438',
                                                          'HUILE DE FRITURE '
                                                          '2*7,5L',
                                                          6,
                                                          117.36],
                                                      [   '4552-064',
                                                          'SAUCE TOMATE ORIGAN',
                                                          1,
                                                          7.78]],
                                         'montant': 1808.97,
                                         'quantite': '123'},
                  '003 EMBALLAGE': {   'items': [   [   '7334-438',
                                                        'MOYEN GOBELET 0,4L',
                                                        1,
                                                        42.38],
                                                    [   '4910-063',
                                                        'BOITE MC FIRST DD',
                                                        1,
                                                        22.99],
                                                    [   '5816-066',
                                                        'BOITE TRIPLE CHEESE '
                                                        'DD',
                                                        1,
                                                        13.71],
                                                    [   '1430-103',
                                                        'BOITE LE 280 ORIGINAL '
                                                        '2019',
                                                        1,
                                                        21.97],
                                                    [   '768-729',
                                                        'GRAND GOBELET 0,5L',
                                                        1,
                                                        46.23],
                                                    [   '6373-783',
                                                        'GOB MCFLURRY NI',
                                                        1,
                                                        19.06],
                                                    [   '117-297',
                                                        'COUV GOB 0,4/ 0,5 L',
                                                        2,
                                                        31.7],
                                                    [   '5478-072',
                                                        'CUILLERE MC FLURRY '
                                                        'COURTE',
                                                        1,
                                                        12.64],
                                                    [   '193-086',
                                                        'SERVIETTES N3',
                                                        1,
                                                        25.35],
                                                    [   '163-656',
                                                        'BOITE MOY.FRITES /17',
                                                        1,
                                                        22.56]],
                                       'montant': 258.59,
                                       'quantite': '11'},
                  '009 ADMINSTR & STAT': {   'items': [   [   '94700-006',
                                                              'DOLLIES '
                                                              'PLASTIQUES '
                                                              'RENDUES',
                                                              -2,
                                                              -39.64],
                                                          [   '94700-007',
                                                              'DOLLIES '
                                                              'PLASTIQUES '
                                                              'LIVREES',
                                                              5,
                                                              99.1],
                                                          [   '94700-012',
                                                              'DEMI PALETTES '
                                                              'RENDUES',
                                                              -8,
                                                              -72.4],
                                                          [   '94700-013',
                                                              'DEMI PALETTES '
                                                              'LIVREES',
                                                              8,
                                                              72.4]],
                                             'montant': 59.46,
                                             'quantite': '3'}},
    'netap': 4536.83,
    'num': '113192',
    'resto': '003690-001532',
    'totalht': 4761.79,
    'totalttc': 5057.92,
    'type': '380'}
    P = ParseurEdi(edi_file)
    assert P.read() == ref_dic